version: '3.3'
services:
  amqp:
    #http://0.0.0.0:15672/#/
    container_name: amqp
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234
