version: '1'
services:
  amqp:
    container_name: amqp
    image: arm64v8/rabbitmq
    restart: always
    ports:
      - 15672:15672
    command:
      - rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp