spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:33306/default
    username: root
    password: 1234